### ISSUE TITLE
0.3.1 doesn't ship the right binary for linux

### ISSUE THREAD

**Issue by rbelouin** [getgauge-contrib/json-report#10]
Hi there :wave:

It seems that the binary of `json-report@0.3.0` has mistakenly been released as `json-report@0.3.1` too.

**How to reproduce:**

```
wget https://github.com/getgauge-contrib/json-report/releases/download/v0.3.1/json-report-0.3.1-linux.x86_64.zip
unzip -d 0.3.1 json-report-0.3.1-linux.x86_64.zip

wget https://github.com/getgauge-contrib/json-report/releases/download/0.3.0/json-report-0.3.0-linux.x86_64.zip
unzip -d 0.3.0 json-report-0.3.0-linux.x86_64.zip

sha1sum 0.3.1/bin/json-report 0.3.0/bin/json-report
```

**Actual result:**

```
f74c6f148458e12f806c2f0fe26cce6d46876143  0.3.1/bin/json-report
f74c6f148458e12f806c2f0fe26cce6d46876143  0.3.0/bin/json-report
```

**Expected result:**

As the execution statuses have changed to past tense, I am expecting the binaries to have a different hash.

**Comment by apoorvam** [comment]
Hi @rbelouin Thanks for reporting this. I have fixed the binaries now with right version. Please re-install it and try out. I'll try automating this soon.
