### ISSUE TITLE
failure screenshot is missing in json report

### ISSUE THREAD

**Issue by dibyaranjan-pg** [getgauge-contrib/json-report#19]
In recent updates to gauge, we are not able to see the screenshot data in json report. Please see the screenshot.
![image](https://user-images.githubusercontent.com/58494847/90477475-18040400-e149-11ea-8903-23333a3beafb.png)

Gauge version details:
Gauge version: 1.1.1
Plugins
-------
html-report (4.0.10)
java (0.7.7)
json-report (0.3.3)
screenshot (0.0.1)
xml-report (0.2.3)

Note: html reports shows failure screenshot, it is only json report has the issue

**Comment by dibyaranjan-pg** [comment]
I found some context here : https://github.com/getgauge/gauge/issues/1476. And it looks like latest Gauge runner is not providing base64 image data to plugins rather writing screenshots to a specific file and letting plugins to take a call how to use the screenshot data. 
It seems the current version of the JSON report does not use the screenshot file and because of that the screenshot image is blank. Can someone help here please?

**Comment by dibyaranjan-pg** [comment]
I have made fix for this and verified, want to discuss if that would be ideal solution for json-report.

**Comment by sriv** [comment]
:clap: that's great @dibyaranjan-pg 

Feel free to put your proposal here (or better, raise a Pull Request, so we can discuss and merge it).

**Comment by dibyaranjan-pg** [comment]
@sriv  thanks for the response. Here is my proposed solution to the issue. As the gauge runner stores failure screenshots as file with latest changes, I am reading the file as byte array and setting it to screenshot property for json report.
Please look at the PR:
https://github.com/getgauge-contrib/json-report/pull/20

**Comment by sriv** [comment]
@dibyaranjan-pg thanks for the pull request, and apologies for the delay.

I've now merged it. Will make a release.

**Comment by sriv** [comment]
fixed via #20 and released in v0.3.5.
