### ISSUE TITLE
"failedScenariosCount" is invalid in the json-report

### ISSUE THREAD

**Issue by osandadeshan** [getgauge-contrib/json-report#9]
This is the json report for my execution.
[result.zip](https://github.com/getgauge-contrib/json-report/files/3137370/result.zip)
 At the end of the file, it shows;
`
"beforeSuiteHookFailure": null,
	"afterSuiteHookFailure": null,
	"passedSpecsCount": 14,
	"failedSpecsCount": 1,
	"skippedSpecsCount": 0,
	"passedScenariosCount": 45,
	"failedScenariosCount": 0,
	"skippedScenariosCount": 0
`
Here "failedSpecsCount": 1 and "failedScenariosCount": 0. 
But the actual scenario failures are 1. This is the error for that failure
`
Errors:
          
            [Parse Error] C:\Program Files (x86)\Jenkins\workspace\MaxSoft IntelliAPI\specs\Other\Form-Data Example.spec:20 Dynamic param  could not be resolved, Missing file: C:/client_id.txt => '   |client_id    |    |'
          
            [Parse Error] C:\Program Files (x86)\Jenkins\workspace\MaxSoft IntelliAPI\specs\Other\Form-Data Example.spec:21 Dynamic param  could not be resolved, Missing file: C:/client_secret.txt => '   |client_secret||'
          
            [Parse Error] C:\Program Files (x86)\Jenkins\workspace\MaxSoft IntelliAPI\specs\Other\Form-Data Example.spec:22 Dynamic param  could not be resolved, Missing file: C:/refresh_token.txt => '   |refresh_token||'
          
`

This is the html-report screenshot
![image](https://user-images.githubusercontent.com/9147189/57066499-f4197680-6ce9-11e9-9f4c-f70a5c5f8528.png)

HTML report also not identified the failure scenario, it also shows failure scenarios are 0

**Comment by osandadeshan** [comment]
@apoorvam Please check this issue. This is still happening in the latest json-report version.

**Comment by apoorvam** [comment]
@osandadeshan Gauge plugins(both html-report and json-report) use the specFailedCount and scenarioFailedCount which is received from Gauge core. I believe if this is an issue, it will need a fix in gauge core. Can you please raise this issue there?

**Comment by osandadeshan** [comment]
@apoorvam I have added the issue in gauge core
https://github.com/getgauge/gauge/issues/1444
